on:
  push:
    branches:
      - main
      - maint/*
    tags:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  needs-review:
    runs-on: ubuntu-latest
    environment: Package deployment
    steps:
      - run: echo "Testing"
